name: CI

on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Run
        env:
          RUNNER_ARCH: ${{ runner.arch }}
        run: |
          bash run.sh && exit 0
